### ISSUE TITLE
Password is stored in plain text

### ISSUE THREAD

**Issue by ericclaeren** [translations-com/glc-m2#1]
Hi,

I have a security issue with this module, the password is not stored correctly, it should have been encrypted, but it's stored in plain text. Anybody with hold of the database could get into your system.

This post should help you with encrypting the password correctly: https://magento.stackexchange.com/a/224910

Regards, Eric

**Comment by justin7griffin** [comment]
Hi Eric,

Anybody who can access our module will have access to the account that this password controls, so this is not really a security issue. Our service is similar to being subscription based.

Thanks!
Justin Griffin

**Comment by ericclaeren** [comment]
Hi @justin7griffin 

Yes it is, unencrypted passwords are always a security issue, **always**.
What in case a client re-used a password (which isn't smart, but probably will occur).

Please explain again? On a production website, with a username and a custom set password in which scenario would you like to expose the password? When having the username. Doesn't this make an attacker be able to log in with the username and password into your service?

Cheers, Eric

**Comment by justin7griffin** [comment]
Passwords in this case are generated by our company and are unique. They are not modifiable by the client. All they enable anybody to do is submit content for translation.

**Comment by justin7griffin** [comment]
I should note that we will investigate changing this as well, but the ramifications of this password being exposed are very low at this time.

**Comment by justin7griffin** [comment]
Hi @ericclaeren,

Both issues will be included starting in version 1.8.4_RC1. We don't currently have a release date set, as we are waiting for Magento 2.4.2's early access to verify there are no other issues that need working on.

Thanks!
Justin

**Comment by ericclaeren** [comment]
Thanks @justin7griffin 

An addition to your reply. You don't have to hack a mysql database, a database backup is damaging enough. So for instance a hacker which scans servers for public accessible sql dumps (which happens more then you may think by lazy dev's on a staging server or just on production) or gain access to a cloud storage where database backups are stored. 

Without having access to Magento, this gives an attacker the possibility to login into your system, insert a xss injection into the translated content and this will be synced back to the website and your client and it's customers are screwed.

Also the password I received for the sandbox environment was not unique in any way, which may be another issue. But the same. A xss injection on a sandbox env is just as damaging. (Although i'm not sure if it's possible to edit translated content in sandbox)

This is now the case for all your Magento clients.

**Comment by ericclaeren** [comment]
Please close the issue after it's released, so I can review the changes. The issue is not resolved yet.

**Comment by justin7griffin** [comment]
Hi Eric,

We do not keep track of issues here; we have our own internal tracking system. Our team will let you know when a build containing these changes is available.

Thanks!
Justin Griffin
